### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by BahlulHasanli** [BahlulHasanli/Padar#1]
### Will be added soon

- [ ] 1. Other String and Numeric data types
- [ ] 2. Formatting codes in the **Migrations.sql** file
- [ ] 3. Improved CLI will be added
